"""envc — local open-env-commons registry CLI (no network)."""

from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from envc import __version__
from envc.device_map import (
    CAPTURE_SCHEMA_ID,
    DEFAULT_CATEGORY,
    SCHEMA_ID,
    device_class_for,
)
from envc.paths import envc_home, registry_dir
from envc.registry import export_index, get_entry, list_entries, publish
from envc.validate import validate_env


def _now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def cmd_init(args: argparse.Namespace) -> int:
    slug = args.slug.strip().strip("/")
    if not slug or "/" in slug or "@" in slug:
        print("error: slug must be a single path segment (e.g. bedroom-phone-scan)", file=sys.stderr)
        return 2
    org = args.org
    version = args.version
    out = Path(args.dir or slug).resolve()
    if out.exists() and any(out.iterdir()):
        print(f"error: directory not empty: {out}", file=sys.stderr)
        return 2
    out.mkdir(parents=True, exist_ok=True)
    (out / "assets" / "visual").mkdir(parents=True, exist_ok=True)
    (out / "assets" / "collision").mkdir(parents=True, exist_ok=True)

    capture_mode = args.capture_mode
    device = device_class_for(capture_mode)
    env_id = f"env:{org}/{slug}@{version}"
    # placeholder 64-char hex (replace on real publish when mcap is present)
    stub_hash = "0" * 64

    manifest = {
        "schema": SCHEMA_ID,
        "id": env_id,
        "name": slug.replace("-", " ").title(),
        "summary": f"{DEFAULT_CATEGORY} scene scaffold for {slug}.",
        "category": DEFAULT_CATEGORY,
        "created_at": _now_iso(),
        "license": {
            "code": "CC-BY-4.0",
            "url": None,
            "notes": "No PII / faces unblurred.",
        },
        "attribution": {
            "contributors": [
                {
                    "name": args.contributor or org,
                    "role": "scene_owner",
                    "contact": "",
                    "share": 1.0,
                }
            ],
            "derived_from": [],
        },
        "capture": {
            "session_id": "replace-with-capture-session-uuid",
            "schema": CAPTURE_SCHEMA_ID,
            "capture_mode": capture_mode,
            "capture_device_class": device,
            "package": {
                "path": f"../captures/session_replace-with-capture-session-uuid/",
                "uri": None,
            },
            "session_mcap_sha256": stub_hash,
            "purpose": "scene",
            "duration_s": 0.0,
            "created_at": _now_iso(),
            "streams_present": ["rgb"],
            "calibration": {"rig_id": "phone_default", "method": "factory"},
        },
        "assets": {
            "visual": {"format": "3dgs", "path": "assets/visual/"},
            "collision": {"format": "mesh_urdf", "path": "assets/collision/"},
            "semantics": {
                "format": "openusd_labels",
                "path": "assets/semantics/",
                "optional": True,
            },
            "previews": {
                "point_cloud_thumb": "assets/preview_pc.jpg",
                "depth_thumb": "assets/preview_depth.jpg",
                "photoreal_still": "assets/preview_rgb.jpg",
            },
        },
        "sim": {
            "targets": ["isaac_lab", "mujoco"],
            "units": "meters",
            "up_axis": "z",
            "origin": "capture_rig",
        },
        "quality": {
            "status": "draft",
            "tags": [],
            "gates_passed": [],
            "notes": "",
        },
        "rewards_hooks": {
            "enabled": False,
            "scheme": None,
            "reputation_weight": None,
        },
    }
    (out / "env.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (out / "LICENSE").write_text(
        "Data in this environment package is licensed under CC-BY-4.0 "
        "unless otherwise noted in env.json.\n",
        encoding="utf-8",
    )
    (out / "NOTICE").write_text(
        f"Environment package scaffold generated by envc {__version__}.\n",
        encoding="utf-8",
    )
    (out / "checksums.sha256").write_text(
        f"# fill after packing assets\n# {stub_hash}  session.mcap\n",
        encoding="utf-8",
    )
    # tiny stub previews so G1 can pass once user keeps them
    import base64

    jpeg = base64.b64decode('/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAABAAEBAREA/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/9oACAEBAAA/AH9G/9k=')
    for name in ("preview_pc.jpg", "preview_depth.jpg", "preview_rgb.jpg"):
        (out / "assets" / name).write_bytes(jpeg)

    print(f"initialized {out}")
    print(f"  id: {env_id}")
    print("  next: edit env.json capture.session_id / package, then `envc validate` / `envc publish`")
    return 0


def cmd_validate(args: argparse.Namespace) -> int:
    report = validate_env(args.path)
    print("\n".join(report.summary_lines()))
    return 0 if report.ok else 1


def cmd_publish(args: argparse.Namespace) -> int:
    try:
        entry = publish(args.path)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 1
    print(f"published {entry['id']}")
    print(f"  path: {entry['path']}")
    print(f"  registry: {registry_dir()}")
    return 0


def cmd_list(_args: argparse.Namespace) -> int:
    entries = list_entries()
    if not entries:
        print(f"(empty) registry at {registry_dir()}")
        return 0
    for e in entries:
        print(f"{e['id']}\t{e.get('quality_status', '')}\t{e.get('name', '')}")
    return 0


def cmd_get(args: argparse.Namespace) -> int:
    try:
        result = get_entry(args.id)
    except KeyError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if args.json:
        print(json.dumps(result, indent=2))
    else:
        entry = result["entry"]
        print(f"id:   {entry['id']}")
        print(f"name: {entry.get('name')}")
        print(f"path: {result['path']}")
        print(f"quality: {entry.get('quality_status')}")
        print("--- env.json ---")
        print(json.dumps(result["manifest"], indent=2))
    return 0


def cmd_export_index(_args: argparse.Namespace) -> int:
    path = export_index()
    print(path)
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="envc",
        description="open-env-commons local registry CLI (filesystem only, no network)",
    )
    p.add_argument("--version", action="version", version=f"envc {__version__}")
    sub = p.add_subparsers(dest="command", required=True)

    init_p = sub.add_parser("init", help="scaffold a new env package directory")
    init_p.add_argument("slug", help="package slug (e.g. bedroom-phone-scan)")
    init_p.add_argument("--org", default="you", help="org/user segment of env id (default: you)")
    init_p.add_argument("--version", default="0.1.0", dest="version", help="semver (default: 0.1.0)")
    init_p.add_argument("--dir", default=None, help="output directory (default: ./<slug>)")
    init_p.add_argument("--capture-mode", default="android", choices=sorted({
        "robot_ros2", "android", "tablet_android", "ios_later"
    }))
    init_p.add_argument("--contributor", default=None, help="scene_owner display name")
    init_p.set_defaults(func=cmd_init)

    val_p = sub.add_parser("validate", help="validate env.json + local gates G0/G1/G4")
    val_p.add_argument("path", nargs="?", default=".", help="package dir or env.json")
    val_p.set_defaults(func=cmd_validate)

    pub_p = sub.add_parser("publish", help="validate + copy into local registry")
    pub_p.add_argument("path", nargs="?", default=".", help="package dir or env.json")
    pub_p.set_defaults(func=cmd_publish)

    list_p = sub.add_parser("list", help="list environments in the local registry")
    list_p.set_defaults(func=cmd_list)

    get_p = sub.add_parser("get", help="fetch a published env by id")
    get_p.add_argument("id", help="env:<org>/<slug>@<semver>")
    get_p.add_argument("--json", action="store_true", help="print full JSON")
    get_p.set_defaults(func=cmd_get)

    exp_p = sub.add_parser("export-index", help="print path to registry.json")
    exp_p.set_defaults(func=cmd_export_index)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    # ensure home exists lazily via commands
    _ = envc_home
    return int(args.func(args))
